### ISSUE TITLE
Expand on handling and displaying post dates

### ISSUE THREAD

**Issue by cmegown** [benbalter/jekyll-style-guide#19]
I'd like to take this on as I've recently been researching how to correctly handle displaying a post's publish date using the `<time>` element. Do we want to have code snippets in the style guide or hold off until there's a "boilerplate" of sorts in progress?

**Comment by benbalter** [comment]
Looks like it should just be `<time datetime="2008-02-14 20:00">`? If you'd like to take a pass at a PR to add it, great, although I'm not sure how common the `time` tag is used (I had to look it up), or if there's any practical benefit?

**Comment by cmegown** [comment]
Well for the most part I'd use `time` semantics and accessibility, it's admittedly unclear if there is any SEO benefit though.
