### ISSUE TITLE
Incorrect statement about site.github.url being overridden by Github Pages

### ISSUE THREAD

**Issue by boturnbow** [benbalter/jekyll-style-guide#27]
I wanted this tip to work: http://ben.balter.com/jekyll-style-guide/config/#url

> Prefer site.github.url when using GitHub Pages. To ensure your site renders properly locally, add the following to your site’s config (**which will be overridden by GitHub Pages**):
> 
> github:
>   url: http://localhost:4000

But when my sites are built at GH pages I find that the value for site.github.url is not overridden. Just for fun, I tried with and without the metadata plug in with the same results.

Thanks for putting this resource together :+1:

**Comment by boturnbow** [comment]
Maybe I jumped the gun. It looks like this PR https://github.com/jekyll/github-metadata/pull/50 when released would eliminate the need for the url section from the docs as the metadata plugin would automatically set site.github.url to localhost for development.

So maybe the documentation changes to just recommending using the plug in?

**Comment by benbalter** [comment]
> So maybe the documentation changes to just recommending using the plug in?

I believe that's correct. I'll try to find some time to update it.
