### ISSUE TITLE
Enhance: layouts-and-includes.md  with examples.

### ISSUE THREAD

**Issue by swizca** [benbalter/jekyll-style-guide#30]
An example of nested layouts would be useful here.

Particularly when encountering compress_html suggestions.

e.g. something along the lines of:
\<_layout/file>: \<Front Matter>
compressed.md: layout default
mydefault.md: layout compressed
mypost.md: layout mydefault

AND ... note the contents of such files. e.g.
\<html>
  {{content}}
\</html>

**Comment by benbalter** [comment]
Given that Liquid 4 has whitespace controls (and most servers including GitHub Pages use Gzip), I don't know that HTML compression is worth the added complexity.
