### ISSUE TITLE
site.github.url and redirect-from

### ISSUE THREAD

**Issue by DirtyF** [benbalter/jekyll-style-guide#6]
>  When your site is intended to be hosted on GitHub Pages, prefer `site.github.url,` to a manually specified `url`...To ensure your site renders properly locally, add the following to your site’s config (which will be overridden by GitHub Pages):

```
github:
  url: http://localhost:4000

```

Given that `site.github.url` is `http://localhost:4000`
and that `permalink: pretty` is set in the `_config.yml`
And that CNAME specifies `frank.taillandier.me`
And that that the site is hosted on Github Pages
And that a post has a `redirect-from: /2016/01/28/comprendre-le-mvp/` specified in the front matter
Then the post URL redirects to `http://localhost:4000/agile//2016/01/28/comprendre-le-mvp/` instead of  http://frank.taillandier.me/agile//2016/01/28/comprendre-le-mvp/

@benbalter I followed your URL setup advice but I ran into trouble with redirections and had to set the `site.github.url` back with the value of the CNAME file. Did I miss something here?

Thanks for this style guide effort, it's definitively useful for Jekyll noobs like me.

**Comment by benbalter** [comment]
For those that come to this issue via Google or elsewhere, I'd recommend using the `absolute_url` and `relative_url` filters in all cases, which will default to the local host and port when previewing (and will be set by GitHub in production).
